using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Luna.Generators;

public static class SyntaxExtensions
{
    public static TypeDeclarationSyntax AddInheritCommentPartial(this TypeDeclarationSyntax syntax)
        => syntax.AddModifiers(SyntaxFactory.Token(SyntaxFactory.TriviaList(SyntaxFactory.Inheritdoc()),
            SyntaxKind.PartialKeyword, SyntaxFactory.TriviaList()));

    extension(string text)
    {
        public SyntaxToken Identifier()
            => SyntaxFactory.Identifier(text);

        public IdentifierNameSyntax IdentifierName()
            => SyntaxFactory.IdentifierName(text);

        public SyntaxTrivia Comment()
            => SyntaxFactory.Comment(text);

        public LiteralExpressionSyntax Literal()
            => SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(text));
    }

    public static CompilationUnitSyntax Normalize(this CompilationUnitSyntax syntax)
        => syntax.NormalizeWhitespace("    ", "\n");


    public static MemberAccessExpressionSyntax EnumValue<T>(this T value, string? enumName = null) where T : Enum
        => SyntaxFactory.MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, (enumName ?? nameof(T)).IdentifierName(),
            SyntaxFactory.Token(SyntaxKind.DotToken), value.ToString().IdentifierName());

    extension(SyntaxFactory)
    {
        public static AttributeSyntax Embedded()
            => SyntaxFactory.Attribute("global::Microsoft.CodeAnalysis.EmbeddedAttribute".IdentifierName());

        public static AttributeSyntax Generated()
            => SyntaxFactory.Attribute("global::System.CodeDom.Compiler.GeneratedCode".IdentifierName())
                .AddArgumentListArguments(
                    SyntaxFactory.AttributeArgument(AssemblyName.Name.Literal()),
                    SyntaxFactory.AttributeArgument(AssemblyName.Version.ToString().Literal()));

        public static FileScopedNamespaceDeclarationSyntax LunaGeneratorsNamespace()
            => SyntaxFactory.FileScopedNamespaceDeclaration("Luna.Generators".IdentifierName())
                .WithLeadingTrivia("// <auto-generated/>".Comment())
                .WithTrailingTrivia(
                    SyntaxFactory.Trivia(SyntaxFactory.PragmaWarningDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.DisableKeyword), true)),
                    SyntaxFactory.Trivia(SyntaxFactory.NullableDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.EnableKeyword), true)));

        public static AttributeSyntax AttributeUsage(AttributeTargets target)
            => SyntaxFactory.Attribute("global::System.AttributeUsage".IdentifierName())
                .AddArgumentListArguments(SyntaxFactory.AttributeArgument(target.EnumValue("global::System.AttributeTargets")));

        public static SyntaxTrivia Inheritdoc()
            => SyntaxFactory.Comment("/// <inheritdoc/>");

        public static SyntaxTriviaList DefaultFileTrivia()
        {
            return SyntaxFactory.TriviaList("// <auto-generated/>".Comment(),
                SyntaxFactory.Trivia(SyntaxFactory.PragmaWarningDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.DisableKeyword), true)),
                SyntaxFactory.Trivia(SyntaxFactory.NullableDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.EnableKeyword), true)));
        }

        public static PropertyDeclarationSyntax CreateProperty(string name, string summary, TypeSyntax type)
            => SyntaxFactory
                .PropertyDeclaration(type, name)
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .AddAccessorListAccessors(
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)))
                .WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Comment($"/// <Summary> {summary} </Summary>")));
    }

    private static readonly AssemblyName AssemblyName = Assembly.GetAssembly(typeof(SyntaxExtensions)).GetName();
}
