using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Luna.Generators;

public static class SyntaxExtensions
{
    public static CompilationUnitSyntax WrapInPartialType(this INamedTypeSymbol type, IEnumerable<MemberDeclarationSyntax> members,
        SyntaxList<UsingDirectiveSyntax> usings = default)
    {
        MemberDeclarationSyntax declaration = CreatePartialType(type, members);
        for (var containing = type.ContainingType; containing is not null; containing = containing.ContainingType)
            declaration = CreatePartialType(containing, [declaration]);

        if (!type.ContainingNamespace.IsGlobalNamespace)
            declaration = SyntaxFactory
                .FileScopedNamespaceDeclaration(GetNamespaceSyntax(type.ContainingNamespace))
                .WithMembers(SyntaxFactory.SingletonList(declaration));

        declaration = declaration.WithLeadingTrivia(SyntaxFactory.DefaultFileTrivia());
        return SyntaxFactory.CompilationUnit()
            .WithUsings(usings)
            .WithMembers(SyntaxFactory.SingletonList(declaration))
            .Normalize();
    }

    extension(TypeDeclarationSyntax template)
    {
        public CompilationUnitSyntax WrapInContainingNamespaces(IEnumerable<MemberDeclarationSyntax> generated, CompilationUnitSyntax root)
        {
            var members = SyntaxFactory.List(generated);
            foreach (var ns in template.Ancestors().OfType<BaseNamespaceDeclarationSyntax>())
            {
                BaseNamespaceDeclarationSyntax wrapper = ns switch
                {
                    NamespaceDeclarationSyntax n           => n.WithMembers(members),
                    FileScopedNamespaceDeclarationSyntax n => n.WithMembers(members),
                    _                                      => throw new InvalidOperationException(),
                };
                members = SyntaxFactory.SingletonList<MemberDeclarationSyntax>(wrapper);
            }

            return SyntaxFactory.CompilationUnit()
                .WithExterns(root.Externs)
                .WithUsings(root.Usings)
                .WithMembers(members);
        }

        public TypeDeclarationSyntax AddInheritCommentPartial()
            => template.AddModifiers(SyntaxFactory.Token(SyntaxFactory.TriviaList(SyntaxFactory.Inheritdoc()),
                SyntaxKind.PartialKeyword, SyntaxFactory.TriviaList()));
    }

    public static CompilationUnitSyntax PrepareGeneratedSource(this CompilationUnitSyntax source)
    {
        var autoGenerated = SyntaxFactory.TriviaList(SyntaxFactory.Comment("// <auto-generated/>"),
            SyntaxFactory.ElasticLineFeed,
            SyntaxFactory.Trivia(SyntaxFactory.NullableDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.EnableKeyword), true)),
            SyntaxFactory.ElasticLineFeed);
        return source.WithLeadingTrivia(autoGenerated);
    }

    extension(string text)
    {
        public SyntaxToken Identifier()
            => SyntaxFactory.Identifier(text);

        public IdentifierNameSyntax IdentifierName()
            => SyntaxFactory.IdentifierName(text);

        public SyntaxTrivia Comment()
            => SyntaxFactory.Comment(text);

        public LiteralExpressionSyntax Literal()
            => SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(text));
    }

    public static CompilationUnitSyntax Normalize(this CompilationUnitSyntax syntax)
        => syntax.NormalizeWhitespace("    ", "\n");


    public static MemberAccessExpressionSyntax EnumValue<T>(this T value, string? enumName = null) where T : Enum
        => SyntaxFactory.MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, (enumName ?? nameof(T)).IdentifierName(),
            SyntaxFactory.Token(SyntaxKind.DotToken), value.ToString().IdentifierName());

    extension(SyntaxFactory)
    {
        public static AttributeSyntax Embedded()
            => SyntaxFactory.Attribute("global::Microsoft.CodeAnalysis.EmbeddedAttribute".IdentifierName());

        public static AttributeSyntax Generated()
            => SyntaxFactory.Attribute("global::System.CodeDom.Compiler.GeneratedCode".IdentifierName())
                .AddArgumentListArguments(
                    SyntaxFactory.AttributeArgument(AssemblyName.Name.Literal()),
                    SyntaxFactory.AttributeArgument(AssemblyName.Version.ToString().Literal()));

        public static FileScopedNamespaceDeclarationSyntax LunaGeneratorsNamespace()
            => SyntaxFactory.FileScopedNamespaceDeclaration("Luna.Generators".IdentifierName())
                .WithLeadingTrivia("// <auto-generated/>".Comment())
                .WithTrailingTrivia(
                    SyntaxFactory.Trivia(SyntaxFactory.PragmaWarningDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.DisableKeyword), true)),
                    SyntaxFactory.Trivia(SyntaxFactory.NullableDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.EnableKeyword), true)));

        public static AttributeSyntax AttributeUsage(AttributeTargets first, params ReadOnlySpan<AttributeTargets> remaining)
        {
            ExpressionSyntax expression = first.EnumValue("global::System.AttributeTargets");
            foreach (var target in remaining)
            {
                expression = SyntaxFactory.BinaryExpression(SyntaxKind.BitwiseOrExpression, expression,
                    target.EnumValue("global::System.AttributeTargets"));
            }

            return SyntaxFactory.Attribute("global::System.AttributeUsage".IdentifierName())
                .AddArgumentListArguments(SyntaxFactory.AttributeArgument(expression));
        }

        public static SyntaxTrivia Inheritdoc()
            => SyntaxFactory.Comment("/// <inheritdoc/>");

        public static SyntaxTriviaList DefaultFileTrivia()
            => SyntaxFactory.TriviaList("// <auto-generated/>".Comment(),
                SyntaxFactory.Trivia(SyntaxFactory.PragmaWarningDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.DisableKeyword), true)),
                SyntaxFactory.Trivia(SyntaxFactory.NullableDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.EnableKeyword), true)));

        public static PropertyDeclarationSyntax CreateProperty(string name, string summary, TypeSyntax type)
            => SyntaxFactory
                .PropertyDeclaration(type, name)
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .AddAccessorListAccessors(
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)))
                .WithLeadingTrivia(SyntaxFactory.TriviaList(SyntaxFactory.Comment($"/// <Summary> {summary} </Summary>")));
    }

    private static readonly AssemblyName AssemblyName = Assembly.GetAssembly(typeof(SyntaxExtensions)).GetName();

    private static TypeDeclarationSyntax CreatePartialType(INamedTypeSymbol type, IEnumerable<MemberDeclarationSyntax> members)
    {
        var declaration = SyntaxFactory.ClassDeclaration(type.Name.Identifier())
            .WithModifiers(SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.PartialKeyword)))
            .WithMembers(SyntaxFactory.List(members));

        if (type.TypeParameters.Length is 0)
            return declaration;

        var list = SyntaxFactory.SeparatedList(type.TypeParameters.Select(static p => SyntaxFactory.TypeParameter(p.Name.Identifier())));
        declaration = declaration.WithTypeParameterList(SyntaxFactory.TypeParameterList(list));
        return declaration;
    }

    private static NameSyntax GetNamespaceSyntax(INamespaceSymbol namespaceSymbol)
    {
        var parts = new List<string>();
        for (var current = namespaceSymbol; !current.IsGlobalNamespace; current = current.ContainingNamespace)
            parts.Add(current.Name);
        parts.Reverse();

        NameSyntax name = parts[0].IdentifierName();
        for (var i = 1; i < parts.Count; ++i)
            name = SyntaxFactory.QualifiedName(name, parts[i].IdentifierName());
        return name;
    }
}
