//HintName: ConfigPropertyAttribute.g.cs
// <auto-generated/>
namespace Luna.Generators;
#pragma warning disable
#nullable enable
/// <summary> Mark a field as a config property so that it invokes a save method and an event on changes. </summary>
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
[global::System.CodeDom.Compiler.GeneratedCode("Luna.Generators", "1.0.0.0")]
[global::System.AttributeUsage(global::System.AttributeTargets.Field)]
internal class ConfigPropertyAttribute : global::System.Attribute
{
    /// <Summary> The name of the generated property. If left null, the capitalized name of the field without leading underscore will be used. </Summary>
    public string? PropertyName { get; set; }
    /// <Summary> An optional name for an event invoked after the property is changed. If left null, the event is omitted. </Summary>
    public string? EventName { get; set; }
    /// <Summary> The name of the save method to invoke on changes. If left null, "Save" will be used. </Summary>
    public string? SaveMethodName { get; set; }
    /// <Summary> Whether to skip calling the save method entirely. </Summary>
    public bool SkipSave { get; set; }
}