//HintName: Config.g.cs
// <auto-generated/>
#pragma warning disable
#nullable enable
/// <inheritdoc/>
partial class Config
{
    /// <inheritdoc cref="_intProp"/>
    public int IntProp
    {
        get => _intProp;
        set
        {
            if (!global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_intProp, value))
            {
                int __oldValue = _intProp;
                OnIntPropChanging(value, _intProp);
                _intProp = value;
                OnIntPropChanged(_intProp, __oldValue);
                IntChanged(_intProp, __oldValue);
                Save();
            }
        }
    }

    /// <summary> Execute logic before <see cref="IntProp"/> changes. </summary>
    /// <param name="newValue"> The new value that is being set. </param>
    /// <param name="oldValue"> The current value that will be changed. </param>
    [global::System.CodeDom.Compiler.GeneratedCode("Luna.Generators", "1.0.0.0")]
    partial void OnIntPropChanging(int newValue, int oldValue);
    /// <summary> Execute logic after <see cref="IntProp"/> changed. </summary>
    /// <param name="newValue"> The new value that has been set. </param>
    /// <param name="oldValue"> The old value that has been changed. </param>
    [global::System.CodeDom.Compiler.GeneratedCode("Luna.Generators", "1.0.0.0")]
    partial void OnIntPropChanged(int newValue, int oldValue);
    /// <summary> Invoked after <see cref="IntProp"/> changed. First argument is the new value, second is the old value. </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Luna.Generators", "1.0.0.0")]
    public event global::System.Action<int, int>? IntChanged;
}